import { Inter } from "next/font/google";
import { SidebarMenu } from "./Components/SidebarMenu";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex last:flex-grow">
        <SidebarMenu />
        {children}
        </body>
    </html>
  );
}
